version: "2.4.1"

services:
  selar:
    build:
      dockerfile: ./dockerfiles/php.dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    container_name: selar.web
    depends_on:
      - redis
    # command: php artisan queue:work
  redis:
    image: redis:alpine3.16
    ports:
      - "6379:6379"
    container_name: selar.redis
